In [5]:
import numpy as np

In [6]:
# 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# 2D array
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 3D array
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

print("\n3D Array:")
print(array_3d)

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
for name, arr in [("1D", array_1d), ("2D", array_2d), ("3D", array_3d)]:
    print(f"{name} array")
    print("Dimensions (ndim):", arr.ndim)
    print("Shape:", arr.shape)
    print("Number of elements (size):", arr.size)
    print("Data type (dtype):", arr.dtype)
    print("-" * 40)

1D array
Dimensions (ndim): 1
Shape: (5,)
Number of elements (size): 5
Data type (dtype): int64
----------------------------------------
2D array
Dimensions (ndim): 2
Shape: (3, 3)
Number of elements (size): 9
Data type (dtype): int64
----------------------------------------
3D array
Dimensions (ndim): 3
Shape: (2, 2, 2)
Number of elements (size): 8
Data type (dtype): int64
----------------------------------------


In [8]:
print("First element:", array_1d[0])
print("Last element:", array_1d[-1])
print("Elements from index 1 to 3:", array_1d[1:4])
print("Every second element:", array_1d[::2])
print("\n2D element at row 1, column 2:", array_2d[1, 2])
print("First row:", array_2d[0, :])
print("Second column:", array_2d[:, 1])
print("Top-left 2x2 section:")
print(array_2d[:2, :2])
print("\n3D element [1, 0, 1]:", array_3d[1, 0, 1])

First element: 10
Last element: 50
Elements from index 1 to 3: [20 30 40]
Every second element: [10 30 50]

2D element at row 1, column 2: 6
First row: [1 2 3]
Second column: [2 5 8]
Top-left 2x2 section:
[[1 2]
 [4 5]]

3D element [1, 0, 1]: 6


In [9]:
original = np.arange(1, 13)
print("Original array:")
print(original)
print("Original shape:", original.shape)
reshaped_2d = original.reshape(3, 4)
print("\nReshaped to 3 x 4:")
print(reshaped_2d)
print("New shape:", reshaped_2d.shape)
reshaped_3d = original.reshape(2, 2, 3)
print("\nReshaped to 2 x 2 x 3:")
print(reshaped_3d)
print("New shape:", reshaped_3d.shape)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original shape: (12,)

Reshaped to 3 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New shape: (3, 4)

Reshaped to 2 x 2 x 3:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
New shape: (2, 2, 3)


In [10]:
zeros_array = np.zeros((2, 3))
ones_array = np.ones((2, 3))
arange_array = np.arange(0, 10, 2)
linspace_array = np.linspace(0, 1, 6)
print("zeros():")
print(zeros_array)
print("\nones():")
print(ones_array)
print("\narange(0, 10, 2):")
print(arange_array)
print("\nlinspace(0, 1, 6):")
print(linspace_array)

zeros():
[[0. 0. 0.]
 [0. 0. 0.]]

ones():
[[1. 1. 1.]
 [1. 1. 1.]]

arange(0, 10, 2):
[0 2 4 6 8]

linspace(0, 1, 6):
[0.  0.2 0.4 0.6 0.8 1. ]


In [11]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a ** 2 =", a ** 2)
print("a % b =", a % b)
print("\nSquare root:", np.sqrt(a))
print("Natural logarithm:", np.log(a))
print("Exponential:", np.exp(np.array([1, 2, 3])))

a + b = [12 24 35 48]
a - b = [ 8 16 25 32]
a * b = [ 20  80 150 320]
a / b = [5. 5. 6. 5.]
a ** 2 = [ 100  400  900 1600]
a % b = [0 0 0 0]

Square root: [3.16227766 4.47213595 5.47722558 6.32455532]
Natural logarithm: [2.30258509 2.99573227 3.40119738 3.68887945]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [12]:

temperatures_c = np.array([20, 25, 30, 35, 40])
temperatures_f = temperatures_c * 9 / 5 + 32
print("Temperature in Celsius:", temperatures_c)
print("Temperature in Fahrenheit:", temperatures_f)
sales = np.array([100, 150, 200, 250])
discounted_sales = sales * 0.90
print("\nOriginal sales:", sales)
print("After 10% discount:", discounted_sales)

Temperature in Celsius: [20 25 30 35 40]
Temperature in Fahrenheit: [ 68.  77.  86.  95. 104.]

Original sales: [100 150 200 250]
After 10% discount: [ 90. 135. 180. 225.]


In [13]:
scores = np.array([45, 67, 82, 91, 56, 74, 38, 88])
passed_mask = scores >= 50
print("Scores:", scores)
print("Pass mask:", passed_mask)
passed_scores = scores[passed_mask]
print("Passed scores:", passed_scores)
high_scores = scores[scores >= 80]
print("Scores >= 80:", high_scores)
medium_scores = scores[(scores >= 50) & (scores < 80)]
print("Scores from 50 to 79:", medium_scores)

Scores: [45 67 82 91 56 74 38 88]
Pass mask: [False  True  True  True  True  True False  True]
Passed scores: [67 82 91 56 74 88]
Scores >= 80: [82 91 88]
Scores from 50 to 79: [67 56 74]


In [14]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
row_values = np.array([1, 2, 3])
print("Matrix:")
print(matrix)
print("\nValues added to each row:")
print(row_values)
result = matrix + row_values
print("\nResult:")
print(result)
print("\nMatrix multiplied by 2:")
print(matrix * 2)

Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Values added to each row:
[1 2 3]

Result:
[[11 22 33]
 [41 52 63]
 [71 82 93]]

Matrix multiplied by 2:
[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]


In [15]:
data = np.array([12, 18, 25, 30, 15, 20, 40, 10])
print("Data:", data)
print("\nSum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

Data: [12 18 25 30 15 20 40 10]

Sum: 170
Mean: 21.25
Minimum: 10
Maximum: 40
Median: 19.0


In [16]:
marks = np.array([
    [80, 75, 90],
    [65, 85, 70],
    [95, 88, 92]
])
print("Marks:")
print(marks)
print("\nColumn-wise sum:", np.sum(marks, axis=0))
print("Row-wise sum:", np.sum(marks, axis=1))
print("\nColumn-wise mean:", np.mean(marks, axis=0))
print("Row-wise mean:", np.mean(marks, axis=1))
print("\nColumn-wise minimum:", np.min(marks, axis=0))
print("Row-wise maximum:", np.max(marks, axis=1))

Marks:
[[80 75 90]
 [65 85 70]
 [95 88 92]]

Column-wise sum: [240 248 252]
Row-wise sum: [245 220 275]

Column-wise mean: [80.         82.66666667 84.        ]
Row-wise mean: [81.66666667 73.33333333 91.66666667]

Column-wise minimum: [65 75 70]
Row-wise maximum: [90 85 95]


In [17]:
student_marks = np.array([
    [78, 85, 92, 88],
    [65, 72, 80, 75],
    [90, 95, 89, 94],
    [55, 68, 60, 70],
    [82, 79, 85, 88]
])
print("Student marks:")
print(student_marks)
student_totals = np.sum(student_marks, axis=1)
student_averages = np.mean(student_marks, axis=1)
print("\nTotal marks for each student:")
print(student_totals)
print("\nAverage marks for each student:")
print(student_averages)
print("\nHighest subject score:", np.max(student_marks))
print("Lowest subject score:", np.min(student_marks))
print("Overall mean:", np.mean(student_marks))
print("Overall median:", np.median(student_marks))
high_performers = student_averages[student_averages >= 80]
print("\nAverages >= 80:", high_performers)

Student marks:
[[78 85 92 88]
 [65 72 80 75]
 [90 95 89 94]
 [55 68 60 70]
 [82 79 85 88]]

Total marks for each student:
[343 292 368 253 334]

Average marks for each student:
[85.75 73.   92.   63.25 83.5 ]

Highest subject score: 95
Lowest subject score: 55
Overall mean: 79.5
Overall median: 81.0

Averages >= 80: [85.75 92.   83.5 ]
